name: Dockerized Python tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  test:
    if: github.event.action != 'closed' || (github.event.pull_request.merged == true && github.event.pull_request.merge_commit_sha != github.event.pull_request.head.sha)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build test image
        run: docker build -t chief-ci .
      - name: Run tests with coverage in Docker
        run: |
          set -euo pipefail
          docker run --rm \
            -v "$PWD":/coverage \
            chief-ci \
            pytest --cov=ChatAssistant --cov-report=xml:/coverage/coverage.xml
      - name: Upload coverage to Codecov
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          verbose: true
