name: Python tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  test:
    if: github.event.action != 'closed' || (github.event.pull_request.merged == true && github.event.pull_request.merge_commit_sha != github.event.pull_request.head.sha)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: pytest --cov=ChatAssistant --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          verbose: true
